export const siteConfig = {
  name: "Pablo García Rius",
  title: "Python Data & Automation Engineer",
  description: "Portfolio website of Pablo García Rius",
  accentColor: "#2563eb",
  social: {
    email: "pablogrius@gmail.com",
    linkedin: "https://www.linkedin.com/in/pablo-rius",
    github: "https://github.com/PabloRius",
  },
  skills: [
    "Python",
    "AWS",
    "Crawlee",
    "Prefect",
    "Pulumi",
    "NixOS",
    "Node.js",
    "TypeScript",
    "CI/CD",
  ],
  projects: [
    {
      slug: "ecommerce-market-intelligence-scraper",
      link: "https://github.com/tu-usuario/proyecto1",
      skills: ["Python", "Crawlee", "Web Automation", "Prefect", "AWS"],
      tags: ["Data Engineering", "Web Scraping", "Cloud"],
      year: 2026,
    },
    {
      slug: "automated-incident-reporting-pipeline",
      link: "https://github.com/tu-usuario/proyecto2",
      skills: ["Node.js", "REST APIs", "Data Pipelines", "Power BI"],
      tags: ["Data Engineering", "Automation", "Business Intelligence"],
      year: 2024,
    },
    {
      slug: "real-time-sensor-data-platform",
      link: "https://github.com/tu-usuario/proyecto3",
      skills: ["Azure IoT", "Node.js", "React", "TypeScript", "Real-time Data"],
      tags: ["IoT", "Full-Stack", "Real-time"],
      year: 2024,
    },
  ],
  experience: [
    {
      slug: "comexsoft-python-engineer",
      company: "ComexSoft",
      dateRange: "January 2026 - Present",
      location: "Biarritz, France & Santiago de Chile, Chile",
    },
    {
      slug: "tk-elevator-bi-analyst",
      company: "TK Elevator",
      dateRange: "June 2024 - December 2024",
      location: "Madrid, Spain",
    },
    {
      slug: "ntt-data-software-engineer",
      company: "NTT DATA",
      dateRange: "September 2023 - May 2024",
      location: "Madrid, Spain",
    },
  ],
  education: [
    {
      slug: "kingston-university-meng",
      school: "Kingston University",
      dateRange: "January 2025 - January 2026",
      location: "London, United Kingdom",
    },
    {
      slug: "uc3m-bsc-computer-science",
      school: "Universidad Carlos III de Madrid",
      dateRange: "September 2019 - July 2024",
      location: "Madrid, Spain",
    },
    {
      slug: "unsw-exchange-computer-science",
      school: "UNSW",
      dateRange: "January 2023 - June 2023",
      location: "Sydney, Australia",
    },
  ],
};
